### ISSUE TITLE
Little issue i ran into.

### ISSUE THREAD

**Issue by Jeisonx3** [val92130/Supreme-Auto-Checkout#11]
First of all thank you very much for your work, it isn't really a big issue don't think is priority to fix but if you use 3 keywords i'm not able to scroll down to add (save) .
<img width="526" alt="screen shot 2017-08-30 at 6 56 07 pm" src="https://user-images.githubusercontent.com/22186712/29898664-09179e9c-8db5-11e7-8004-e66f69bc2e55.png">

also when i open the extension it automatically opens in the autocop page (if autocop was the last option used), the size of the option is too small for me to input the other options i have to close and reopen the extension, click the billing option to get the extension size to readjusts.

<img width="703" alt="screen shot 2017-08-30 at 7 00 54 pm" src="https://user-images.githubusercontent.com/22186712/29898748-97b0cdae-8db5-11e7-84ce-d396cb805382.png">

<img width="705" alt="screen shot 2017-08-30 at 7 00 39 pm" src="https://user-images.githubusercontent.com/22186712/29898765-a775a5d4-8db5-11e7-9857-a84b189fb7c8.png">

EDIT 2: Also i see no size option for the hats category http://www.supremenewyork.com/shop/all/hats, and a One size/No Size option in accessories for items with no size. 
Like this one: http://www.supremenewyork.com/shop/accessories/nwmbu0po8/x5amrbdhp

**Comment by val92130** [comment]
Hey,
Thanks for this detailled issue!
I've been able to reproduce the issues, I'll look into that asap.

I haven't added a size option for hats because I didn't know they had different sizes but in fact they do, I'll work on adding that option soon.

As for accessories with no sizes option they should be added to cart automatically no matter what size you chose in the options, have you encoutered issues with this?

Regards,
Val

**Comment by Jeisonx3** [comment]
Accessories (items) with no size indeed are added to cart automatically with any size selected thanks.

**Comment by val92130** [comment]
I fixed the scroll issue in the ATC product form on the "develop" branch, it will be on the next release probably later today!
As for the other issue concerning the height of the ATC page you can right click on the bot icon and click "options" to open the configuration page in full size, it should do the trick until I fix it.

**Comment by Jeisonx3** [comment]
Thanks.

**Comment by val92130** [comment]
Check out the latest version of the bot https://github.com/val92130/Supreme-Auto-Checkout/releases/tag/v2.2.1

It contains the fix for the scroll in the ATC product form and also adds a new feature for AutoCop !

**Comment by Jeisonx3** [comment]
Sorry to keep bringing this up didn't want to open a new issue but am not able to scroll again in the billing and size option.

**Comment by val92130** [comment]
Have you installed the latest version? (2.2.2)
Could you try to uninstall any version you might have then reinstall the latest? I am currently not able to reproduce this issue

**Comment by Jeisonx3** [comment]
i have version 2.2.2 even used the yarn build command to build it, and used the chrome store and the same problem. Install the chrome store you should be able to reproduce it.

**Comment by val92130** [comment]
I have installed the Chrome store version and I cannot reproduce it.. Could you take some screenshots of the issue? Does the problem persist when you right click the extension's icon and click "Options"?

**Comment by val92130** [comment]
Also, please check if you have any errors in your browser's javascript console

**Comment by Jeisonx3** [comment]
When i right click and click option it works, the problem happens if i click the extension.
<img width="701" alt="screen shot 2017-09-01 at 2 20 10 am" src="https://user-images.githubusercontent.com/22186712/29957557-221a4252-8ebc-11e7-8b05-c1a0be4ef544.png">

**Comment by val92130** [comment]
Could you try to right-click the extension icon, then "inspect popup", it should open another window with a javascript console. In the console type `document.querySelector('#app').style.overflowY = 'scroll';` then enter.
Tell me if it changes anything

**Comment by Jeisonx3** [comment]
after doing that scrolling works, but if i leave the extension open if i close it and reopen it (click) scrolling stops working.
<img width="904" alt="screen shot 2017-09-01 at 2 45 50 am" src="https://user-images.githubusercontent.com/22186712/29958269-cfffbf52-8ebf-11e7-93e3-7b5dda683e35.png">

**Comment by Jeisonx3** [comment]
i can easily fix this by right clicking and using options this isn't really a big issue.

**Comment by val92130** [comment]
Could you try with the latest release ? https://github.com/val92130/Supreme-Auto-Checkout/releases/tag/v2.2.3 I think it might fix the issue.

**Comment by Jeisonx3** [comment]
Fixed!!!!

**Comment by val92130** [comment]
Nice! I'm glad to hear :)
