### ISSUE TITLE
Bot auto fill

### ISSUE THREAD

**Issue by Asuggestion** [val92130/Supreme-Auto-Checkout#112]
Most new bots at the moment will enter the information letter by letter to avoid detection when purchasing items. Will this be a feature on this new bot as i really like it but don't want to get declined on checkout. Thanks

**Comment by val92130** [comment]
Hey, from many tests i've ran, Supreme also detects when entering informations letter by letter using a chrome extension, as far as I know there is no reliable way to bypass this but I'll try my best! :)
