### ISSUE TITLE
Couldn't find a package.json file

### ISSUE THREAD

**Issue by Bedvin1** [val92130/Supreme-Auto-Checkout#121]
Hello. I think I found a way for bot to work. It requires one more app and some scripts, so its a little clumsy but i think it might work.
For that I need to change your bot a bit. But when I try to build a project I get "error An unexpected error occurred: "Couldn't find a package.json file in \"C:\\\\Users\\\\Supreme-Auto-Checkout-master\""."
Im total zero in javascript, could you tell me how to fix this?

**Comment by val92130** [comment]
Hey! The package.json file is located in the `bot` folder
