### ISSUE TITLE
Development build: API key stolen

### ISSUE THREAD

**Issue by miko007** [val92130/Supreme-Auto-Checkout#132]
Your API tells me "API key stolen", when running a self-build version which ist not from the chrome store. How is one supposed to develop, if this is the case/your model?

**Comment by val92130** [comment]
Hey! sorry for the delayed answer. Unfortunately I was facing major issues with users using my api for other bots such as CopBot and were using all the bandwith of my server, causing issues with the restock monitor.
The only solution for me was to limit the usage of the api to requests coming from the official extension :(

Sorry for the issue it has caused you

**Comment by miko007** [comment]
@val92130 could't you put the functionality of your API into the client code?

**Comment by frxncisjoseph** [comment]
@miko007 It wouldn't be viable, specially with restocks. Hosting an API your self allows you to properly cache and store data (i.e. stock). You could implement this yourself using SupCommunity's website through scraping but that doesn't guarantee 100% uptime...

**Comment by val92130** [comment]
@miko007 yeah as @frxncisjoseph said it wouldnt be viable and would also be risky for users since monitoring Supreme's website could lead to a ban :/

I might open-source the api again soon tho

**Comment by mcaustin1** [comment]
@val92130 I have a server or two running that I am willing to host the API on. Email me at mrmcaustin1@gmail.com for me details.

**Comment by frxncisjoseph** [comment]
@mcaustin1 He's not having an issue running the server, he's currently working on it himself...
