### ISSUE TITLE
The drop list is not loading

### ISSUE THREAD

**Issue by acangaroo** [val92130/Supreme-Auto-Checkout#136]
When you click the "Drops"-button, the content is "Loading", but nothing is displayed.

![drops-not-loading](https://user-images.githubusercontent.com/29423795/42124910-4e0ca3e8-7c6c-11e8-87d6-690b8b3914dd.png)

**Comment by val92130** [comment]
Thanks for reporting! It was the ssl certificate for openaio that had expired, it is now fixed :)
