### ISSUE TITLE
Could not load manifest "icon.png"

### ISSUE THREAD

**Issue by SirLovejoy** [val92130/Supreme-Auto-Checkout#155]
chaque fois que je télécharge et essaie de glisser-déposer dans le dossier des extensions, je continue à avoir cette erreur: impossible de charger le manifeste "icon.png"?

**Comment by SirLovejoy** [comment]
obtenir également cette erreur lors du chargement sans emballage .....
Impossible de charger l'icône 'assets / img / icon.png' pour l'action du navigateur.
Impossible de charger le manifeste.

**Comment by val92130** [comment]
You need to build the bot with `npm` before trying to install the bot.
You can do it with `npm install` then `npm run build`

**Comment by SirLovejoy** [comment]
THANK YOU SO MUCH !
