### ISSUE TITLE
Chrome prevent from unauthenticated script

### ISSUE THREAD

**Issue by CabbageUVa** [val92130/Supreme-Auto-Checkout#159]
Hi, I was trying to paly this this extention. For some reason I could not auto-cop and auto-checkout. I CAN "run once" and auto checkout, but cannot do bulk/timed auto-run, since the chrome will then prevent unauthenticated script from running. 

Any idea on how to deal with this? I've unchecked the "safe browsing" on chrome but that doesn't help...

Thanks!

**Comment by aabbccsmith** [comment]
I've made a PR to fix this issue. Hold on tight :D

**Comment by aabbccsmith** [comment]
@CabbageUVa update, try starting chrome with this command (windows only):
`chrome --disable-web-security --allow-running-insecure-content --user-data-dir="C:/ChromeDevSession"`

**Comment by CabbageUVa** [comment]
> @CabbageUVa update, try starting chrome with this command (windows only):
> `chrome --disable-web-security --allow-running-insecure-content --user-data-dir="C:/ChromeDevSession"`

Ha, thanks works

**Comment by aabbccsmith** [comment]
Please re open this issue. The fix I provided is a dirty workaround not a proper fix.

**Comment by CabbageUVa** [comment]
> Please re open this issue. The fix I provided is a dirty workaround not a proper fix.

Reopened.. Thanks for following up!

**Comment by aabbccsmith** [comment]
@CabbageUVa should note, and I know it's probably a little late, removing web security is never a good idea, and you shouldn't ever really do it. I'm sure I won't need to go through the implications, but it can cause you some major issues. Afaik, the newest update (today, an hour ago) addresses this problem (looks at @val92130 to double check) and so you should be good to go for the Bandana Bogos this week.

**Comment by CabbageUVa** [comment]
Thanks for still watching this! I tried out just now, and it works with the auto-bot feature. Chrome doesn't block it anymore. However, it stops working if I put color option... Tried with a few random staffs, if I chose specific color, it would stop and won't continue with next product in list. But I guess that's another issue.   Will resolve this. Thanks @val92130 and @aabbccsmith

**Comment by aabbccsmith** [comment]
All good, glad I could help
