### ISSUE TITLE
Autocheckout not working

### ISSUE THREAD

**Issue by dshet** [val92130/Supreme-Auto-Checkout#163]
the auto checkout function does not open the correct link anymore.

**Comment by romanbird** [comment]
Likewise. I've found its the ? links that cause an issue.

**Comment by dshet** [comment]
Were you able to fix it?

**Comment by romanbird** [comment]
Removing the ?atc-id from the url made the auto cop refresh work at first but not even that’s working today, worth a shot though.

**Comment by val92130** [comment]
Hey, sorry for the lack of support lately, I have updated the bot, it should be working fine now, let me know !
