### ISSUE TITLE
Bot does not automatically "agree" upon payment (Japan)

### ISSUE THREAD

**Issue by nqarubik** [val92130/Supreme-Auto-Checkout#17]
Bot does not automatically "agree" upon payment (Japan)
![untitled23131](https://user-images.githubusercontent.com/31370784/30003664-363991b2-90eb-11e7-9f79-b973275d2450.png)

**Comment by val92130** [comment]
Hey, thanks for reporting! I'll fix that asap

**Comment by nqarubik** [comment]
<3

**Comment by val92130** [comment]
Hey, I have not been able to reproduce this issue on the Japanese store, have you tried with the latest version of the bot?

**Comment by nqarubik** [comment]
oh, i tried it and it works very well <3
thanks you 👍

**Comment by val92130** [comment]
Perfect!
