### ISSUE TITLE
terms 

### ISSUE THREAD

**Issue by kieran0123** [val92130/Supreme-Auto-Checkout#18]
the terms and conditions auto tick doesn't work

**Comment by val92130** [comment]
Hi, I can't seem to reproduce this issue, is it on the EU or US shop? Also, do you have the latest release installed?

**Comment by kieran0123** [comment]
Eu shop and I got the version off the Google store yesterday

**Comment by val92130** [comment]
Do you have any error in the javascript console while on the checkout page? (f12 to open)

**Comment by kieran0123** [comment]
It's fine now I've fixed it my pc was just glitching is all
