### ISSUE TITLE
Bot doesnt work

### ISSUE THREAD

**Issue by Jaysway** [val92130/Supreme-Auto-Checkout#24]
It was working just a few days ago, but now whenever I go to the Supreme website, the bot does not work. I've tried uninstalling it and reinstalling it, updating chrome, and the text at the top where it says if auto-checkout or auto-payment is enabled or not isn't there. It was working perfectly fine a couple of days ago.

**Comment by Jaysway** [comment]
https://gyazo.com/4f42cca495f4814ecbd7c24c01ab2429

**Comment by val92130** [comment]
Hey, could you open the Javascript console (type f12 then 'Console'), refresh the Supreme page and check if there are any errors?

**Comment by Jaysway** [comment]
Yeah
https://gyazo.com/fe19c9082967719a3998455424411942

**Comment by val92130** [comment]
Thanks, the problem is with the 'Hide sold out products', I'll fix this asap! 

Meanwhile you can disabled this option and see if this works.

**Comment by Jaysway** [comment]
Yeah I turned it off and the text at the top of the website works! Thank you!
