### ISSUE TITLE
AutoCop not working

### ISSUE THREAD

**Issue by dytis** [val92130/Supreme-Auto-Checkout#34]
I set the time and test it out on http://www.supremenewyork.com/shop/accessories/wsg79hu0i/gdmtp6vn0 multiple times, and when the time comes it does open up a new tab but get the following drop:

<img width="1245" alt="screen shot 2017-09-25 at 1 43 54 pm" src="https://user-images.githubusercontent.com/32278541/30830120-b414b09a-a1f7-11e7-972a-5693f11e04b7.png">

Could I be doing something wrong? Thank you!

**Comment by val92130** [comment]
Hey! I just tested it with your settings and it seems to be working fine, have you tried by clicking the 'run now' button in the Autocop Products list ?

**Comment by Jeisonx3** [comment]
seem to be on the same boat.
<img width="1358" alt="screen shot 2017-09-25 at 6 56 56 pm" src="https://user-images.githubusercontent.com/22186712/30834947-fdf2508c-a201-11e7-86a8-3642d9fa464b.png">

**Comment by dytis** [comment]
@val92130 Yes I have! That's odd.. Am I supposed to be on a specific site before hitting run? Since it just opens up a new tab, shouldn't matter right? Once it opens a new tab and hits that link (http://supremenewyork.com/shop/170793?atc-color=White), what is it that's supposed to show? Is it a real url set by Supreme?

**Comment by val92130** [comment]
That’s really weird I never had this issue.. what country are you in? Could you also try with the “use product monitor for atc” option ?

**Comment by rel0ading** [comment]
@dytis it seems like supreme may have banned you (maybe just temp), as it says connection refused. Could be for refreshing to much or smth?

**Comment by dytis** [comment]
@val92130 I'm in the US. Just gave it a try again and still got the same:

<img width="1232" alt="screen shot 2017-09-26 at 11 00 57 am" src="https://user-images.githubusercontent.com/32278541/30876024-27b1ff1e-a2aa-11e7-9722-014ada24c3ac.png">

<img width="791" alt="screen shot 2017-09-26 at 11 01 04 am" src="https://user-images.githubusercontent.com/32278541/30876029-2c9e0fa4-a2aa-11e7-8900-8c9a8ca65d2c.png">

**Comment by dytis** [comment]
@rel0ading Could be a possibility. Is there a way to check for certain? I tried going by searching in Google and I'm able to get on the site by the way. But what is http://supremenewyork.com/shop/170793?atc-color=White supposed to direct to? Is it the link to the actual item page?

**Comment by rel0ading** [comment]
http://supremenewyork.com/shop/170793 is the link to the item and ?atc-color=White is telling the bot the color way. Dunno why you cant load, when you can load via google

**Comment by val92130** [comment]
Yeah it's weird, could you maybe try with a proxy or a vpn extension like "Hola vpn" ?

**Comment by dytis** [comment]
@val92130 @rel0ading Worked! Is it possible to cop via "Hola vpn" on the drop day? Or is it too slow? Also any suggestions as to how to unban or reset the ban? Thanks a lot!

**Comment by val92130** [comment]
I don’t know about the unban but yeah you can cop using Hola! It’s gonna be slower tho :/

**Comment by JunyuT** [comment]
not sure on how true it is, but it seems that supreme has been banning IPs that poll the website way too often. The links that are posted up here all work for me.

**Comment by val92130** [comment]
Closing this since it's probably an issue on Supreme's  end.
