### ISSUE TITLE
Bot not working optimal

### ISSUE THREAD

**Issue by rel0ading** [val92130/Supreme-Auto-Checkout#38]
I noticed autocop only refreshes once, so if it dosent find the item, it should refresh again, this delay should be customizable. :)

**Comment by val92130** [comment]
Hey :)

The bot normally refreshes until a matching product is found, it worked on today's drop but I'll see if I can reproduce the issue!

But I agree that the delay should be customizable so I'm gonna work on that!

Were you able to cop anything using the bot? :)

**Comment by val92130** [comment]
Added in 2.8
