### ISSUE TITLE
Droplist

### ISSUE THREAD

**Issue by rel0ading** [val92130/Supreme-Auto-Checkout#46]
Holy moly! I just saw that you added it and wow, amazing.
Also your site, openaio is looking really cool too.

About the droplist, there are some extra spaces, which i assume is because your api dosent accept slashes and special charracters? Anyways, i suggest removing extra spaces (two spaces after eachother) or decoding the text and then back again. Also, i just want to let you know that it is actually possible to get the category from the droplist :) I dont know how youre fetching everything from the site, but on each card, there is a `<p class="category hidden">sweatshirts</p>` :)

It looks awesome! keep up the fantastic work

**Comment by val92130** [comment]
Hey man! Thanks, you're right about the extra spaces and all, I rushed the api and droplist to make it in a day so it's not perfect yet, I'll make it better when I have more time and I'll use your suggestion for the categories :)

For info I use supremecommunity for my api to get infos about the drop!

**Comment by val92130** [comment]
Fixed in api!
