### ISSUE TITLE
Restock Sniper

### ISSUE THREAD

**Issue by CreatingMazes** [val92130/Supreme-Auto-Checkout#47]
Restock Sniper that could maybe link to https://supremecommunity.com/restocks/eu/ or whichever region you're in?

**Comment by val92130** [comment]
Hey, good idea! I didn't know about that, I'll try to implement it in the next updates

**Comment by CreatingMazes** [comment]
Awesome, thanks. 
Really want to cop some more boxers 👍 
What's in and when's the new update coming?

**Comment by val92130** [comment]
The next update will probably include restock notifications, more billing options like complimentary address and enhancements on Autocop!

**Comment by CreatingMazes** [comment]
Sweeeet. 
Do you reckon Paypal support is far fetched or...?

Thanks so much.

**Comment by CreatingMazes** [comment]
Ah yeah good point x) 
Any idea exactly how fast the bot can complete an order for one item from start to finish? 🌊

**Comment by val92130** [comment]
It depends on your internet connection but if you disable all delays it should be between 1 and 2 seconds!

**Comment by CreatingMazes** [comment]
If we disable all delays isn't there a chance supreme could catch us for botting though?

**Comment by val92130** [comment]
Yeah exactly, that's why for hyped drops it's recommend to put a add to cart delay of like 600ms and a checkout delay of 4000ms!

**Comment by CreatingMazes** [comment]
Awesome, will probably use those settings religiously then haha. 
Would you be interested in a Community Manager for this project? Maybe get some more exposure on Twitter and harvest a nice community around this lovely extension.

**Comment by val92130** [comment]
Thanks for the offer man I really appreciate it but unfortunately I already have someone on my team who's handling all that! :)

We currently have a website, a twitter and an instagram account!

**Comment by CreatingMazes** [comment]
Oh right aha fairs.

When do you reckon the next update of the extension will come out then? Really looking forward to it.

**Comment by val92130** [comment]
It should be out wendsday if I can finish in time! :)

**Comment by val92130** [comment]
Implemented in 2.8
