### ISSUE TITLE
Retry Count if not found?

### ISSUE THREAD

**Issue by jeffreykwon44** [val92130/Supreme-Auto-Checkout#62]
What should I do if I want to cop one item really bad?
What should I put in if I want to cop two items really bad?

**Comment by val92130** [comment]
Hi,
The "retry count if not found" means that the bot will refresh the page for n times until a product matching the keywords is found.

If you wanna make sure to cop all the items you want, I recommend you to put a retry count of 10 on each products and set an ATC start time of 10:59:58 if your drop is at 10am.

However if you wanna cop a single product then you can put anything in the retry count and at 11:59:50 or so click the 'run now' button on the Autocop product you want, this will keep refreshing the page until the product is found :)
