### ISSUE TITLE
Captcha bypass

### ISSUE THREAD

**Issue by J1mmyV** [val92130/Supreme-Auto-Checkout#66]
What are the correct settings to improve the capcha bypass probability? Is it totally random? Does doing a captcha test before running the bot authorise your browser and won't display captcha?

Thanks
Keep up with the great work :)

**Comment by val92130** [comment]
Hey!

Yeah the best you can do to avoid captcha would be to log into your google account prior to the drop and resolve some captchas on a captcha testing website :)
