### ISSUE TITLE
Autofill

### ISSUE THREAD

**Issue by manbearcoon** [val92130/Supreme-Auto-Checkout#67]
Been reading that Supreme is blocking autofill and/or detecting autofill which results in your order not going through.

I've seen some tools (restocks app) change it up by actually typing the form data automatically rather than autofill everything. Might be worth implementing in order to avoid order declines.

**Comment by val92130** [comment]
Hey!

I heard that restocks has been blocked from Supreme because of their Autofill but I don’t think my bot will have this issue because I trigger the « focus » event of each field to simulate human interaction. 
It worked great on the last drop and didn’t have any issue checking out :)
