### ISSUE TITLE
Auto-checkout (dev branch)

### ISSUE THREAD

**Issue by own2pwn** [val92130/Supreme-Auto-Checkout#68]
Hi, if I haven't bothered you yet: currently I'm on a dev branch, I disabled auto-checkout but when I'm on basket [page](http://www.supremenewyork.com/shop/cart) bot still redirects me to a checkout. Is it correct behavior?

**Comment by val92130** [comment]
Hi, yes for the moment it is the expected behaviour but I'm thinking of another way of doing that, do you have any ideas?

**Comment by own2pwn** [comment]
What if we add some flag(bool) to proceed auto-checkout when we running auto-cop?

**Comment by val92130** [comment]
Yeah that could be nice! Do you want to try to implement it and make a pull-request?

**Comment by own2pwn** [comment]
Or maybe a simpler solution: track if we've visited checkout page at least once and do redirect based on this check?
but we need to decide where/when to reset this check

**Comment by own2pwn** [comment]
I could try but I haven't got any real experience with JS as well as with Chrome ext. I could try to dig into it at weekend

**Comment by val92130** [comment]
Yeah that would be cool! I don't have much as much time as before to work on the bot
