### ISSUE TITLE
Can't check cart, keeps going check out.

### ISSUE THREAD

**Issue by iwant2cop** [val92130/Supreme-Auto-Checkout#75]
Hi, I've noticed with the new 2.9 update that it wont allow me to check the cart even if autocop and autopay are turned off. The only way I am actually able to view the cart is by disabling the extension. This never happened before until the 2.9 update.

**Comment by iamjunmo** [comment]
same problem

**Comment by val92130** [comment]
Thanks for reporting this! This is indeed a bug caused by the 2.9 update, I’ll fix this ASAP, hopefully before today’s drop.

**Comment by val92130** [comment]
It should now be fixed! Autocop will redirect you to your cart if you have autocheckout disabled, you'll be able to check your cart before paying :)
Let me know if there is any issue!

**Comment by CreatingMazes** [comment]
Thanks! 💃 

What's the website for this btw?
