### ISSUE TITLE
Preventing Card Decline

### ISSUE THREAD

**Issue by lkjhgfdsas** [val92130/Supreme-Auto-Checkout#78]
Firstly, thank you for creating a great bot and continuing to update it.

Recently many people in the Supreme community have been experiencing card decline errors due to Supreme being able to detect autofill. From what I understand the detection can be avoided through manually filling the CVV before clicking checkout.

The bot currently doesn't allow you to leave the CVV blank in the billing settings page so my suggestion is to allow it to be saved as blank. On drop day the bot can add all the items to cart, fill the address and card info but **not** the CVV. People can then manually enter their CVV and click checkout avoiding the detection.

**Comment by val92130** [comment]
Hey, thanks man great idea!
I think I'm gonna let the user decided which field he wants to manually fill, so I'm going to remove the required attribute of all fields of the billing tab, what do you think?

**Comment by lkjhgfdsas** [comment]
Yeh I think that definitely would work. Thanks man.
