### ISSUE TITLE
Size Feature Not Working

### ISSUE THREAD

**Issue by hsolish** [val92130/Supreme-Auto-Checkout#8]
Hello,
For some reason, whenever I have autocheckout enabled and I click on a product, it will just autommaticaly take the smallest size available and add to cart, even though I put size Large in the sizing option and size Large is available. It appears it just adds the first it can to cart. Is there a way to stop this? Thanks.

**Comment by val92130** [comment]
Hi,
Thanks for your support,
Do you have the latest version installed? If so, try to uninstall it then reinstall it, sometimes some old data from older versions can be kept in the local storage.
If you do not have the latest release I recommend you to install it and see if the problem persists.

Could you also provide me the product or the category of the product you were trying to add to cart?
I just reinstalled the lastest version and so far the bot adds the correct size to the cart.

Also, was it on the EU store or US store?

Thanks,
Val

**Comment by val92130** [comment]
You're welcome, I'm glad it works!

I'll release a new version of the bot before this thursday's drop with features such as enhanced checkout, multi-profiles and an auto-cop feature with product keywords, make sure to check it out so you can give your feedback!

Val
