### ISSUE TITLE
I wanna join the Chinese work

### ISSUE THREAD

**Issue by rainzee** [val92130/Supreme-Auto-Checkout#87]
Hey u done a great job for Supreme fans

In China theres is so many user and i wanan help it translate it

**Comment by val92130** [comment]
Hey! Thanks for your interest in the project :)

I saw that some people already translated it in Chinese here: http://www.supreme007.com/2017/11/28/supreme-bot-1-1.html

I don't know if it's free since I can't read chinese but if you want to make your own then feel free to fork the projet! :) If you need help for anything just ask me and I will try my best to help you.

**Comment by rainzee** [comment]
This is a website that for  China Supreme fans But this is not a non-profit organization ：（

They translate Vulnerable and Has been unable to run they even added a password for it u only need to follow they website and wechat and They tampered with the introduction and added they own website.

i do not think a good program should be treated like this although they keep donation page and Express your thanks but i really thins it's a bad work cause it just can run in sone Specific environment

So i wanan help it make clean and sexy just like oringinal

**Comment by val92130** [comment]
Oh okay I understand :( so feel free to edit the program as you want! Let me know if you have any issue with the translation

**Comment by chitichine** [comment]
D'abord, je vous remercier votre projet qui nous aide énormément ( franchement je prépare bien l'achat de Supreme TNF avec votre bot） 
je pense que le mec chinois avait mis le bot sur sa plateforme (gratuit pour le téléchargement) pour maximiser les demandes de tous les fans chinois supreme , en plus il appréciait énormément votre projet et votre personnalité éminente pendant le vidéo qui introduit les fonctionnements de votre projet , mais aussi il ajoutais certain trucs dans vote projet  pour faire connaître sa plateforme  en même temps que cela introduit les fonctionnements de votre projet ,
 en tout cas , je vous indiquerai ce qu'il se passerai après, merci bp

**Comment by rainzee** [comment]
After several hours of continuous work I completed the finished work i almost did not sleep all night

I can be proud to say that this is absolutely the best Chinese version

Every single word every translation is done after I deep understanding and my own experiment completed I translated it into an easy-to-understand and concise  beautiful Chinese any one chinese can understand it and use it just like local software

I have not only translated the surface, any notification, hidden tips, illegal tips, including hard to detect buttons I have translated In addition to translation, all the functional description I have used a more detailed Chinese description, to make sure  that everyone can understand

Everything else, keep oringinal, without any modification, unlike some websites that are filled with external links and ugly icons and Induce users to visit their websites and wechat  and place labels everywhere just like Afraid of other people do not know this is what they do

After this work i found it soooo beautiful with simple chinese without any other mess 

A good software should be treated like this

BTW i do not use GITHUB i don't know how to submit changes just like GIT？

**Comment by chitichine** [comment]
good job !!! you are the best programmers all in chinese supreme fans：)

**Comment by val92130** [comment]
Thanks @rainzee that seems really promising! You should try to publish your work on Github! :)

**Comment by rainzee** [comment]
I'v already upload on github u can check it out
