### ISSUE TITLE
japan

### ISSUE THREAD

**Issue by nqarubik** [val92130/Supreme-Auto-Checkout#9]
Can you add japanese stroe?

**Comment by val92130** [comment]
Hi,

Japan is available in the country list of the bot, but I haven't had the opportunity to try it as I don't have a Japan proxy yet.

Have you been able to try it? If so, please tell me what issues you encountered with the bot and I'll try to fix them ASAP.

Regards,
Val

**Comment by nqarubik** [comment]
Supreme japan allows COD
Please add it

**Comment by val92130** [comment]
I'm sorry but what is COD ?

**Comment by nqarubik** [comment]
Cash On Delivery

**Comment by val92130** [comment]
Okay I see, I just tested the japanese version of the store using a VPN and there are indeed some different options for checkout.

I'll try to implement it for the next release tonight, I added it on my to-do list.
I'll keep you updated when it's done!

**Comment by nqarubik** [comment]
Let me ask more:
Ever update AUTOCOP?

**Comment by val92130** [comment]
Yes, AutoCop is set to release tonight along with a Multi-Profiles feature!

You can already check the progress on the "develop" branch of the project.

**Comment by nqarubik** [comment]
Wow, i really like it <3

**Comment by nqarubik** [comment]
You have used social network?

So that I can track easier

**Comment by nqarubik** [comment]
It is still free or charged ?

**Comment by val92130** [comment]
It will always be free!

My goal with this project was to bring a free, open-source and powerful bot.

**Comment by nqarubik** [comment]
Great, thank you very very much <3

**Comment by nqarubik** [comment]
I will support you if you open donate <3

**Comment by val92130** [comment]
Thanks a lot, I really appreciate it!

I'll let you know when Japan support is added, it should be done in a few hours.

**Comment by nqarubik** [comment]
thanks you so much <3
my email: tatvomom124@gmail.com

**Comment by val92130** [comment]
The support for Japan is now done!

I pushed the update on the "develop" branch, it will get released with the new bot update that should be out in a few hours.
