### ISSUE TITLE
Supreme added Autofill Detection!

### ISSUE THREAD

**Issue by martijnbrands** [val92130/Supreme-Auto-Checkout#98]
Supreme added Autofill Detection to there site. Is it possible that we simulate human keyboard typing? To prevent that Supreme detects the bot. Maybe we can add Typed.js to tackle this problem.

**Comment by val92130** [comment]
Hey! Unfortunatly this isn't something we can do with a Chrome extension, and typed.js only animates typing but doesn't really simulate it.

**Comment by martijnbrands** [comment]
Right now all the billing information gets filled in at the same time. If the bot can type each character 
individually (so Supreme things the bot is a human) we may can bypass the autofill detection.

**Comment by val92130** [comment]
I tried to do this unfortunately Supreme detects bot by listening on "keypress" events, and those events cannot be simulated by a chrome extension

**Comment by xxxsomethingxd** [comment]
what about fillr? supreme doesn't detect fillr
